### PR TITLE
refactored project to be multi-doc

### PR DESCRIPTION
**Pull request by wildthink**
Completely refactored the project in creating a multi-document version. Names are now “Replete” instead of “Replete-macos” and the c-code was refactored to cleanup all the warnings which (I think) fixed a bug or two that had yet manifested itself

### CODE REVIEW

**Review by mfikes — CHANGES_REQUESTED** [review]
Looks good in general with respect to explicitly passing the JavaScriptCore context around.

One thing that you probably didn't intend and should be fixed before merging is that the contents in `bundle.c` are being committed. I suspect this is because the file is now in a new location and the Git trickery here isn't working:

https://github.com/replete-repl/replete-macos/blob/c2dc89a073f4b0da1740866a3cb48f3393309d93/ClojureScript/replete/script/clean#L10

I think to fix this would involve getting the original `bundle.c` file contents and putting _that_ into this PR in the new location, and revising that bit of the script. (This may take two commits to get right... not sure.)

**Comment by mfikes** [comment]
Also, when fixing the `bundle.c` issue, I'd recommend squashing at some point. (The file in the PR is currently huge.)

**Comment by wildthink** [comment]
The replete-ios bundle.c has includes that are different from that of the built bundle.c herein. Namely

macos/bundle.c
```
#include <stdlib.h>
#include <string.h>

#include <zlib.h>
```

and
ios/bundle.c
```
#include <stdio.h>
```

Which should we prefer?

**Comment by mfikes** [comment]
The headers can be set to be whatever they need to be. It looks like the large file has already been committed. (See https://raw.githubusercontent.com/replete-repl/replete-macos/master/Replete/bundle.c)

Compare with the initial file in replete-ios, which is small: https://github.com/replete-repl/replete-ios/blob/master/Replete/bundle.c

**Comment by mfikes** [comment]
I think the easiest way to fix this large 10-MB file commit is to rewrite history where it was introduced. If you'd like me to take care of that, let me know. (This could just be merged and then the large file aspect could be taken care of after the fact.)

**Comment by wildthink** [comment]
That would be great if you don't mind. My skills are not what they should be.

**Comment by mfikes** [comment]
Will take care of it.

**Comment by mfikes** [comment]
@wildthink I managed to sort out the `CSContext/bundle.c` by rewriting a little history. (So, you'd need to re-fresh your checkout for the latest---perhaps re-checkout.)

If you now do a `script/build`, the `bundle.c` file will end up with the bundled contents, but they won't be set up to be committed into Git. Then, if you do a `script/clean` the `bundle.c` will be restored.

I haven't yet been able to sort out how to deal with the initial `Repelte/bundle.c` file. We may just have to add a commit that deletes it and live with it being in the history. But I'll try a bit more before I completely give up. I'll let you know if this leads to me wanting to rewrite history again.

**Pull request merged**
