### PR TITLE
It is possible to auto-eval on enter before engine ready

### LINKED ISSUE #54: It is possible to auto-eval on enter before engine ready
Like https://github.com/replete-repl/replete-ios/issues/136, but much more difficult to encounter as computers are so much faster than mobile devices and the engine initializes in about a second. But, nevertheless, if you are really fast, you can repro this.

### PR DESCRIPTION
**Pull request by mfikes**
Fixes #54

### CODE REVIEW

**Comment by wildthink** [comment]
Looking over this, I think 
1) we should wait to load the masthead until everything is initialized, and
2) Be explicit with a "not yet initialized" error with a Beep() and/or an Alert
instead of just the delay however small it may be.

**Comment by mfikes** [comment]
Yeah, that would be a valid approach.

Here's my thinking on things:

The way Replete iOS works (especially catering to older devices) is that it launches the UI and makes it live as quickly as possible. On ancient devices it could be many seconds before the ClojureScript runtime is up. But the UI goes live before that.

So, it shows the masthead immediately, and lets the user start typing in a form immediately. Then the question becomes: "When can the user eval?" Replete iOS has an eval button that is disabled until eval is possible. In typical use, especially on semi-modern iOS devices, you end up in a situation where the ClojureScript runtime initializes while the user is typing the form, and I suspect that many users don't even realize that the button is disabled for a while.

Now, with Replete macOS, the desire to have it auto-eval if the user hits return when the caret after the end of the form is simply motivated by the fact that physical keyboard input is the dominant way it is used. This tweak makes the experience more natural, and I've ported it to Replete iOS, just for consistency—I guess people use physical keyboards with iOS sometimes as well.

I guess this auto-eval upon return is somewhat orthogonal to the issue related to the ClojureScript runtime initializing, but it does interact a bit, especially on mobile, where you have an eval button that may still be disabled (so it introduces a situation where the user can "jump the gun" and essentially request an eval, even though the ClojureScript runtime is not yet up).

On the iOS side, I have it simply blocking (doing the same thing in this PR), and it seems to be working out nicely, especially on new devices. I'm gonna try it on an old iPad 2, which I think will stress this design, with it perhaps locking the UI for many seconds for most users.

At a high level, I think that the design surrounding this is probably more important to get right on mobile, because that's where the greatest chance of blocking, or some other interaction (like beeping, notifying, etc.) is needed.

Replete macOS is luckier in that, since things are so fast, the design in this PR really doesn't create as many concerns as it does on iOS—thing just appear to work on Replete macOS, and you have to really start a new window and type very quickly to see any blocking at all.

So, it might be worth waiting to see how all of this shakes out on mobile.

There's an open PR (https://github.com/replete-repl/replete-android/pull/43) for Android, where it is not even clear whether it is possible to block, and instead a return simply acts like a return. And, while the same stuff has landed on Replete iOS master, it isn't yet clear to me whether it is ideal, given the latencies involved on mobile.

**Comment by mfikes** [comment]
@wildthink There is a demo of the "blocking" feature on an iPad 2 over here https://github.com/replete-repl/replete-ios/pull/137#issuecomment-493694037

(To be honest, it actually turns out to be better than I had thought it might be; the blocking is not for very long.)

**Comment by wildthink** [comment]
Lets go ahead with the current fix. It aligns better and to be honest its hardly likely to be a thing at all on the desktop.

**Pull request merged**
